In [223]:
import numpy as np
import scipy
import matplotlib.pyplot as plt
import math
import scipy.linalg
import pandas as pd

Task 1
====
Write a function that can determine the number of ammonia produced at equilibrum for a given set of temperature and pressure conditions.

Example values:

| Temperature, T (K) | Pressure, p (atm) | delta_H_T  | delta_S  | Equilibrium constant, K | Moles Ammonia, y |
|--------------------|-------------------|------------|----------|-------------------------|------------------|
| 298                | 1                 | -91873.247 | -198.068 | 572920.561              | 1.936            |

In [57]:
def calc_delta_H(T):
  return (405000/T)-55.169*T + 0.024928*(T**2)-6.587*(10**(-7))*(T**3)-78988.22

calc_delta_H(298)

-91873.24705336583

In [58]:
def calc_delta_S(T):
  return -55.169*(math.log(T)) + 0.049856*T + 202500/T**2 - 9.88*10**(-7) * T**2 + 99.185

calc_delta_S(298)

-198.0682982199486

In [59]:
def calc_delta_G(T):
  return calc_delta_H(T) - (T*calc_delta_S(T))

calc_delta_G(298)

-32848.894183821154

In [64]:
def calc_K(T):
  R = 8.3143 # Gas constant 
  ln_K = calc_delta_G(T)/(-R*T)
  K = math.e**ln_K
  return K

calc_K(298)

572646.5424848114

In [66]:
def calc_n_of_moles(p, T):
  K = calc_K(T)
  numerator = (math.sqrt(6912*K)*p) - (108*K*p**2)
  denuminator = (27*K*p**2) - 16
  y = 2 - math.sqrt((numerator/denuminator)+4)
  return y

calc_n_of_moles(90, 800)

0.2834582443839031

# Task 2

`Pressure cost = a + bp + cp**2 + dp**3`

In [114]:
def load_values_from_file():
  df = pd.read_csv('pressure_costs.csv', delimiter="\t", header=[1], index_col=0)
  return df['Pressure (atm)'].tolist(), df['Price (pence per mole N2)'].tolist()
  
  
pressures, costs = load_values_from_file()

In [116]:
print(pressures, costs)

[1, 11, 21, 31, 41, 51, 61, 71, 81, 91, 101, 111, 121, 131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391] [0.099833, 0.106378, 0.095623, 0.083062, 0.101047, 0.083212, 0.065943, 0.078018, 0.066597, 0.055665, 0.051916, 0.051891, 0.038059, 0.057627, 0.027467, 0.034278, 0.04346, 0.03756, 0.035421, 0.05111, 0.06927, 0.05474, 0.083585, 0.09558, 0.093021, 0.13147, 0.146948, 0.160558, 0.189714, 0.200011, 0.229131, 0.284326, 0.315686, 0.343619, 0.384935, 0.427707, 0.478444, 0.526763, 0.598935, 0.649119]


In [202]:
def get_coefficients(As, Bs):
  A = np.array(As)
  B = np.array(Bs)
  X = np.linalg.solve(As,Bs)
  a,b,c,d = X

  return a,b,c,d

In [203]:
As = []
Bs = []
for (p, c) in zip(pressures, costs):
  As.append([1, p, p**2, p**3])
  Bs.append(c)

In [204]:
print(As[:5])
print(Bs)

[[1, 1, 1, 1], [1, 11, 121, 1331], [1, 21, 441, 9261], [1, 31, 961, 29791], [1, 41, 1681, 68921]]
[0.099833, 0.106378, 0.095623, 0.083062, 0.101047, 0.083212, 0.065943, 0.078018, 0.066597, 0.055665, 0.051916, 0.051891, 0.038059, 0.057627, 0.027467, 0.034278, 0.04346, 0.03756, 0.035421, 0.05111, 0.06927, 0.05474, 0.083585, 0.09558, 0.093021, 0.13147, 0.146948, 0.160558, 0.189714, 0.200011, 0.229131, 0.284326, 0.315686, 0.343619, 0.384935, 0.427707, 0.478444, 0.526763, 0.598935, 0.649119]


In [205]:
A = np.array(As)
B = np.array(Bs)
X = np.linalg.solve(A,B)
X

LinAlgError: Last 2 dimensions of the array must be square

In [206]:
print(get_coefficients(As,Bs))

LinAlgError: Last 2 dimensions of the array must be square

# Junk

In [198]:
np.linalg.inv(np.array(As))

LinAlgError: Last 2 dimensions of the array must be square

In [200]:
np.array(As).shape

(40, 4)

In [201]:
np.array(Bs).shape[-2:]

(40,)

In [185]:
Q.shape

(40, 4)

In [186]:
R.shape

(4, 4)

In [7]:
round((0.0046*0.0046)/(0.0954*0.0454), 4)

0.0049

In [8]:
(1**2)/1*1**3

1.0

In [12]:
math.log(18114063211264.973)

30.52770972551113

In [120]:
print(p,c)

391 0.649119


In [ ]:
with open('pressure.csv', 'r') as pressure_data:
  print(pressure_data.read())

In [107]:
num = [11, 121, 1331, _]
print(np.poly1d(num))

/opt/homebrew/lib/python3.9/site-packages/numpy/core/shape_base.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ary = asanyarray(ary)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# More junk

In [207]:
m = 6
n = 4
A = np.random.randn(m,n)
b = np.random.randn(m)

In [215]:
A

array([[-0.65650525, -0.65370318,  0.48713573,  0.6523276 ],
       [ 0.17853521, -0.98431425, -1.75710569, -0.04241615],
       [-0.01580253,  0.33280995, -0.75355181,  0.54716121],
       [-0.77442647,  0.22780946, -0.35837135, -0.28068945],
       [-0.9252654 ,  0.48111729,  0.41570029, -0.69162979],
       [ 1.09709384, -0.22486958, -1.07321186, -0.58087767]])

In [216]:
b

array([ 0.37032943,  0.10030699, -0.33180584, -0.30748556,  2.13966166,
        0.7742645 ])

In [208]:
np.linalg.solve(A, b)

LinAlgError: Last 2 dimensions of the array must be square

In [212]:
Q, R = np.linalg.qr(A)

In [213]:
Q

array([[-0.37151868, -0.59824625,  0.32828441,  0.22533649],
       [ 0.10103372, -0.72397131, -0.54996978, -0.11115753],
       [-0.00894271,  0.25153678, -0.53087745,  0.71076109],
       [-0.43825072,  0.05647274, -0.47576045, -0.13366126],
       [-0.52361101,  0.22688884, -0.18738435, -0.52401961],
       [ 0.62084934, -0.00533787, -0.21557093, -0.37312768]])

In [214]:
R

array([[ 1.76708545, -0.35092831, -1.07867977, -0.12701064],
       [ 0.        ,  1.31063019,  0.8709292 , -0.39158703],
       [ 0.        ,  0.        ,  1.85027422,  0.33536291],
       [ 0.        ,  0.        ,  0.        ,  1.15729539]])

In [217]:
Q.shape

(6, 4)

In [218]:
R.shape

(4, 4)

In [224]:
x = scipy.linalg.solve_triangular(R, Q.T.dot(b), lower=False)

In [225]:
np.linalg.norm(A.dot(x)-b,2)

1.6568439004770565

In [227]:
np.linalg.norm(R.dot(x) - Q.T.dot(b))

1.3877787807814457e-17

In [228]:
Q2, R2 = np.linalg.qr(A, mode="complete")

In [230]:
x2 = scipy.linalg.solve_triangular(R[:n], Q.T[:n].dot(b), lower=False)

In [231]:
np.linalg.norm(A.dot(x)-b, 2)

1.6568439004770565

In [232]:
np.linalg.norm(R2.dot(x2) - Q2.T.dot(b))

1.6568439004770568

In [233]:
x - x2

array([0., 0., 0., 0.])

In [234]:
x3 = np.linalg.solve(A.T.dot(A), A.T.dot(b))

In [235]:
x3

array([-0.44828697, -0.42499423,  0.1432789 , -1.32426095])