In [223]:
import numpy as np
import scipy
import matplotlib.pyplot as plt
import math
import scipy.linalg
import pandas as pd

Task 1
====
Write a function that can determine the number of ammonia produced at equilibrum for a given set of temperature and pressure conditions.

Example values:

| Temperature, T (K) | Pressure, p (atm) | delta_H_T  | delta_S  | Equilibrium constant, K | Moles Ammonia, y |
|--------------------|-------------------|------------|----------|-------------------------|------------------|
| 298                | 1                 | -91873.247 | -198.068 | 572920.561              | 1.936            |

In [57]:
def calc_delta_H(T):
  return (405000/T)-55.169*T + 0.024928*(T**2)-6.587*(10**(-7))*(T**3)-78988.22

calc_delta_H(298)

-91873.24705336583

In [58]:
def calc_delta_S(T):
  return -55.169*(math.log(T)) + 0.049856*T + 202500/T**2 - 9.88*10**(-7) * T**2 + 99.185

calc_delta_S(298)

-198.0682982199486

In [59]:
def calc_delta_G(T):
  return calc_delta_H(T) - (T*calc_delta_S(T))

calc_delta_G(298)

-32848.894183821154

In [64]:
def calc_K(T):
  R = 8.3143 # Gas constant 
  ln_K = calc_delta_G(T)/(-R*T)
  K = math.e**ln_K
  return K

calc_K(298)

572646.5424848114

In [66]:
def calc_n_of_moles(p, T):
  K = calc_K(T)
  numerator = (math.sqrt(6912*K)*p) - (108*K*p**2)
  denuminator = (27*K*p**2) - 16
  y = 2 - math.sqrt((numerator/denuminator)+4)
  return y

calc_n_of_moles(90, 800)

0.2834582443839031

# Task 2

`Pressure cost = a + bp + cp**2 + dp**3`

In [114]:
def load_values_from_file():
  df = pd.read_csv('pressure_costs.csv', delimiter="\t", header=[1], index_col=0)
  return df['Pressure (atm)'].tolist(), df['Price (pence per mole N2)'].tolist()
  
  
pressures, costs = load_values_from_file()

In [116]:
print(pressures, costs)

[1, 11, 21, 31, 41, 51, 61, 71, 81, 91, 101, 111, 121, 131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251, 261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381, 391] [0.099833, 0.106378, 0.095623, 0.083062, 0.101047, 0.083212, 0.065943, 0.078018, 0.066597, 0.055665, 0.051916, 0.051891, 0.038059, 0.057627, 0.027467, 0.034278, 0.04346, 0.03756, 0.035421, 0.05111, 0.06927, 0.05474, 0.083585, 0.09558, 0.093021, 0.13147, 0.146948, 0.160558, 0.189714, 0.200011, 0.229131, 0.284326, 0.315686, 0.343619, 0.384935, 0.427707, 0.478444, 0.526763, 0.598935, 0.649119]


In [202]:
def get_coefficients(As, Bs):
  A = np.array(As)
  B = np.array(Bs)
  X = np.linalg.solve(As,Bs)
  a,b,c,d = X

  return a,b,c,d

In [268]:
future_A = []
future_B = []
for (p, c) in zip(pressures, costs):
  future_A.append([1, p, p**2, p**3])
  future_B.append(c)
  
As = np.array(future_A)
Bs = np.array(future_B)

In [273]:
Q, R = np.linalg.qr(As)
print(Q.shape)
print(R.shape)

(40, 4)
(4, 4)


In [274]:
np.linalg.inv(R)

array([[-1.58113883e-01, -2.68467963e-01, -3.33183551e-01,
         3.71900898e-01],
       [ 0.00000000e+00,  1.36973450e-03,  5.20537052e-03,
        -1.19856933e-02],
       [-0.00000000e+00, -0.00000000e+00, -1.32790064e-05,
         7.72059162e-05],
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -1.31302579e-07]])

In [270]:
print(Bs.shape)

(40,)


In [276]:
A = np.array(As[:5])
B = Bs
X = np.linalg.solve(Q,B)
X

LinAlgError: Last 2 dimensions of the array must be square

In [206]:
print(get_coefficients(As,Bs))

LinAlgError: Last 2 dimensions of the array must be square

# Junk

In [198]:
np.linalg.inv(np.array(As))

LinAlgError: Last 2 dimensions of the array must be square

In [200]:
np.array(As).shape

(40, 4)

In [201]:
np.array(Bs).shape[-2:]

(40,)

In [185]:
Q.shape

(40, 4)

In [186]:
R.shape

(4, 4)

In [7]:
round((0.0046*0.0046)/(0.0954*0.0454), 4)

0.0049

In [8]:
(1**2)/1*1**3

1.0

In [12]:
math.log(18114063211264.973)

30.52770972551113

In [120]:
print(p,c)

391 0.649119


In [ ]:
with open('pressure.csv', 'r') as pressure_data:
  print(pressure_data.read())

In [107]:
num = [11, 121, 1331, _]
print(np.poly1d(num))

/opt/homebrew/lib/python3.9/site-packages/numpy/core/shape_base.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ary = asanyarray(ary)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# More junk

In [245]:
#m = 6
#n = 4
A = np.array([[1, 1, 1, 1], [1, 11, 121, 1331], [1, 21, 441, 9261], [1, 31, 961, 29791], [1, 41, 1681, 68921]])
b = np.array([0.099833, 0.106378, 0.095623, 0.083062, 0.101047])
m = 5
n = 4

In [246]:
A

array([[    1,     1,     1,     1],
       [    1,    11,   121,  1331],
       [    1,    21,   441,  9261],
       [    1,    31,   961, 29791],
       [    1,    41,  1681, 68921]])

In [247]:
b

array([0.099833, 0.106378, 0.095623, 0.083062, 0.101047])

In [248]:
np.linalg.solve(A, b)

LinAlgError: Last 2 dimensions of the array must be square

In [249]:
Q, R = np.linalg.qr(A)

In [250]:
Q

array([[-4.47213595e-01, -6.32455532e-01,  5.34522484e-01,
        -3.16227766e-01],
       [-4.47213595e-01, -3.16227766e-01, -2.67261242e-01,
         6.32455532e-01],
       [-4.47213595e-01,  1.19313164e-16, -5.34522484e-01,
        -7.08708833e-16],
       [-4.47213595e-01,  3.16227766e-01, -2.67261242e-01,
        -6.32455532e-01],
       [-4.47213595e-01,  6.32455532e-01,  5.34522484e-01,
         3.16227766e-01]])

In [251]:
R

array([[-2.23606798e+00, -4.69574275e+01, -1.43331957e+03,
        -4.88826821e+04],
       [ 0.00000000e+00,  3.16227766e+01,  1.32815662e+03,
         5.25886775e+04],
       [ 0.00000000e+00,  0.00000000e+00,  3.74165739e+02,
         2.35724415e+04],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         3.79473319e+03]])

In [252]:
Q.shape

(5, 4)

In [253]:
R.shape

(4, 4)

In [254]:
x = scipy.linalg.solve_triangular(R, Q.T.dot(b), lower=False)

In [255]:
np.linalg.norm(A.dot(x)-b,2)

0.0020149163896159236

In [256]:
np.linalg.norm(R.dot(x) - Q.T.dot(b))

5.785374313523152e-17

In [257]:
Q2, R2 = np.linalg.qr(A, mode="complete")

In [258]:
x2 = scipy.linalg.solve_triangular(R[:n], Q.T[:n].dot(b), lower=False)

In [259]:
np.linalg.norm(A.dot(x)-b, 2)

0.0020149163896159236

In [260]:
np.linalg.norm(R2.dot(x2) - Q2.T.dot(b))

0.002014916389615942

In [261]:
x - x2

array([0., 0., 0., 0.])

In [262]:
x3 = np.linalg.solve(A.T.dot(A), A.T.dot(b))

In [263]:
x3

array([ 9.67460381e-02,  3.07828483e-03, -2.36138643e-04,  3.98716667e-06])